import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
b = np.array([10,9,8,7,6,5,4,3,2,1])

print("Addition:", a+b)
print("Subtraction:", a-b)
print("Multiplication:", a*b)
print("Division:", a/b)
print("Power:", a**2)
print("Square Root:", np.sqrt(a))
print("Log:", np.log(a))
print("Exp:", np.exp(a))

print("Max:", np.max(a))
print("Min:", np.min(a))
print("Sum:", np.sum(a))
print("Mean:", np.mean(a))
print("Median:", np.median(a))
print("Std Dev:", np.std(a))
print("Var:", np.var(a))
print("Argmax:", np.argmax(a))
print("Argmin:", np.argmin(a))

print("Unique:", np.unique(a))
print("Sort:", np.sort(a))
print("Reshape 2x5:", a.reshape(2,5))
print("Reshape 5x2:", a.reshape(5,2))
print("Transpose:", np.transpose(a.reshape(2,5)))
print("Flatten:", a.reshape(2,5).flatten())

print("Dot:", np.dot(a.reshape(2,5), b.reshape(5,2)))
print("Matrix Multiply:", a.reshape(2,5) @ b.reshape(5,2))

print("Zeros:", np.zeros((3,3)))
print("Ones:", np.ones((3,3)))
print("Eye:", np.eye(3))
print("Arange:", np.arange(0,20,2))
print("Linspace:", np.linspace(0,1,5))
print("Random:", np.random.rand(3,3))
print("Randint:", np.random.randint(1,10,(3,3)))

m = np.array([[1,2],[3,4]])
n = np.array([[5,6],[7,8]])
print("Matrix Add:", m+n)
print("Matrix Sub:", m-n)
print("Matrix Mul:", m*n)
print("Matrix Dot:", np.dot(m,n))
print("Matrix Inverse:", np.linalg.inv(m))
print("Matrix Determinant:", np.linalg.det(m))
print("Matrix Eigenvalues:", np.linalg.eig(m)[0])
print("Matrix Eigenvectors:", np.linalg.eig(m)[1])
